name: Docs
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Build and Commit
        id: deployment
        uses: sphinx-notes/pages@v3
        with:
          publish: false
      - name: Push changes
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ steps.deployment.outputs.artifact }}
