name: Slow tests

on:
  schedule:
    # Every weekday at 03:49 UTC, see https://crontab.guru/
    - cron: "49 3 * * 1-5"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.8"]

    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Install dependencies
        run: |
          sudo apt update -y
          sudo apt install graphviz
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Install
        run: |
          python -m pip install --no-deps -e .

      - name: Run tests
        run: |
          pytest -vs -k slow --runslow
