name: Tests

on:
  push:
    branches:
      - "main"
  pull_request:
  workflow_dispatch:

concurrency:
  group: Tests-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-12", "windows-latest"]
        python-version: ["3.9"]
        PIP_FLAGS: [""]
        include:
          - os: "ubuntu-latest"
            python-version: "3.12"
          - os: "ubuntu-latest"
            python-version: "3.12"
            PIP_FLAGS: "--pre"

    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Setup Graphviz
        uses: ts-graphviz/setup-graphviz@v2
        with:
          macos-skip-brew-update: 'true'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Install
        run: |
          python -m pip install ${PIP_FLAGS} -e .[test]
        env:
          PIP_FLAGS: ${{ matrix.PIP_FLAGS }}

      - name: Run tests
        env:
          COVERAGE_CORE: sysmon
        run: |
          if [ "$RUNNER_OS" == "Windows" ]; then
            pytest -v
          else
            pytest -v --cov=cubed --cov-report=term-missing --cov-fail-under=90
          fi
        shell: bash
